### ISSUE TITLE
GetAmount function in BaiFileHelper

### ISSUE THREAD

**Issue by ghost** [kenwilcox/BankFileParsers#3]
I have a couple sample files, and one of them was blowing up on line 

`amount = amount.Insert(amount.Length - GetDecimalPlaces(currencyCode), ".");`

in function GetAmount

I just added a if(amount.length > 1) to protect against exception

```
     public static decimal GetAmount(string amount, string currencyCode)
        {
            if (string.IsNullOrEmpty(amount)) return 0;
            if (amount.Length > 1)
             amount = amount.Insert(amount.Length - GetDecimalPlaces(currencyCode), ".");
            return decimal.Parse(amount);
        }

```

**Comment by kenwilcox** [comment]
Interesting - I was having the same issue with an empty or missing amount so that's why the

```
if (string.IsNullOrEmpty(amount)) return 0;
```

was added. Maybe a better thing would be to get the return value of GetDecimalPlaces and make sure the amount.Length is >= the returned value.

Maybe something like this

```
var neededLength = GetDecimalPlaces(currencyCode);
if (string.IsNullOrEmpty(amount) && amount.Length < neededAmount) return 0;
amount = amount.Insert(amount.Length - neededLength, ".");
return decimal.Parse(amount);
```

I don't have Visual Studio handy so I'm not sure it will work.

If you make that change, make a Pull Request and I'll merge it in. If not I should be able to get to it in a day or two. Thanks!

**Comment by kenwilcox** [comment]
I fixed it by doing
`if (amount.Length < neededLength) amount = amount.PadLeft(neededLength+1, '0');`
That way if a value of 7 is passed in 0.07 would be returned - if your currency code is USD - no data loss.

**Comment by kenwilcox** [comment]
Updated Nuget with 0.1.5 - Thanks
