### ISSUE TITLE
BaiTranslator.Translate Text property removes commas

### ISSUE THREAD

**Issue by jacobschellenberg** [kenwilcox/BankFileParsers#9]
The Text property data is filled, but all the commas are removed. Specifically from 88 records.

**Comment by kenwilcox** [comment]
I believe you're seeing something funny, but I'm not sure what it could be. I don't recall removing anything (most of this code was written in 2015), but there could be something. Are you using the Parser or the Translator? I do know the Parser will parse the BAI file, and it will re-write the same file so I don't believe that is removing anything. The Translator could be though since I do know there are places that split the line on a comma.

**Comment by jacobschellenberg** [comment]
I'm using the parser, then putting it through the translator.

I think that it's happening when the "88" continuation lines are processed. It's like it splits on the ',' (comma) to remove the 88, but that also means any text in there that has commas is also removed.
